services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: javabet
      POSTGRES_PASSWORD: javabet
      POSTGRES_DB: javabet
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: